<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="INIT" Id="{95930908-939b-4ce5-b594-bd7cbf91376c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INIT
VAR
    SetPosition_delay     	  :TON;
	SetPosition2getCurrentPositiondelay     	  :TON;
	init_State: INT;
	initStatus: BOOL;
	Axis1_MC_SetPosition: MC_SetPosition;
	Axis2_MC_SetPosition: MC_SetPosition;
	//Axis1
	setpositionAxis1_State: INT;
	PositionSetValue_Axis1:REAL;
	btn_SetPosition_Axis1:BOOL;
	SetPosition_delay_Axis1:TON;
	PositionSetDone_Axis1:BOOL;
	//Axis2
	setpositionAxis2_State: INT;
	PositionSetValue_Axis2:REAL;
	btn_SetPosition_Axis2:BOOL;
	SetPosition_delay_Axis2:TON;
	PositionSetDone_Axis2:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//
//1.初始化：加载保存的persistent变量：位置，并写入当前位置
//
SetPosition_delay.PT:=T#0.1S;
SetPosition_delay();
A_SetPositionMC();
CASE init_State OF 
	0:
		IF NOT Axis1_running AND NOT  Axis2_running THEN
			init_State:=1;
		END_IF
	1:
		IF NOT initStatus THEN
			Axis1_MC_SetPosition.Position:=Axis1_CurrentPosition_retain;
			Axis2_MC_SetPosition.Position:=	Axis1_CurrentPosition_retain;
			Axis1_MC_SetPosition.Execute:=TRUE;
			Axis2_MC_SetPosition.Execute:=TRUE;
			SetPosition_delay.IN:=TRUE;
			init_State:=2;
		END_IF
	2:
		IF Axis1_MC_SetPosition.Done THEN //AND Axis2_MC_SetPosition.Done THEN
			init_State:=88;
		END_IF
		IF SetPosition_delay.Q THEN//延时结束时，还没有设置位置成功
			init_State:=-100;
		END_IF
	88:
		initStatus:=TRUE;
		Axis1_MC_SetPosition.Execute:=FALSE;
		Axis2_MC_SetPosition.Execute:=FALSE;
		SetPosition_delay.IN:=FALSE;
		init_State:=0;
	-100:
		initStatus:=FALSE;
		SetPosition_delay.IN:=FALSE;
		Axis1_MC_SetPosition.Execute:=FALSE;
		Axis2_MC_SetPosition.Execute:=FALSE;
END_CASE

//
//2.位置写入后，当前位置和速度即从轴中获取
//
IF initStatus THEN
	Axis1_CurrentPosition_retain  :=LREAL_TO_REAL(axis1.NcToPlc.ActPos);
	Axis1_Currentvelocity  :=LREAL_TO_REAL(axis1.NcToPlc.ActVelo);
	Axis2_CurrentPosition_retain  :=LREAL_TO_REAL(axis2.NcToPlc.ActPos);
	Axis2_Currentvelocity  :=LREAL_TO_REAL(axis2.NcToPlc.ActVelo);
END_IF

//
//3.任意时刻，通过btn_SetPosition可以设置当前位置
//
//Axis1
SetPosition_delay_Axis1.PT:=T#0.1S;
SetPosition_delay_Axis1();
IF btn_SetPosition_Axis1 THEN
	CASE setpositionAxis1_State OF 
		0:
			IF NOT Axis1_running THEN
				setpositionAxis1_State:=1;
			END_IF
		1:
			Axis1_MC_SetPosition.Position:=PositionSetValue_Axis1;
			Axis1_MC_SetPosition.Execute:=TRUE;
			SetPosition_delay_Axis1.IN:=TRUE;
			setpositionAxis1_State:=2;
		2:
			IF Axis1_MC_SetPosition.Done THEN
				setpositionAxis1_State:=88;
			END_IF
			IF SetPosition_delay_Axis1.Q THEN//延时结束时，还没有设置位置成功
				setpositionAxis1_State:=-100;
			END_IF
		88:
			PositionSetDone_Axis1:=TRUE;
			Axis1_MC_SetPosition.Execute:=FALSE;
			SetPosition_delay_Axis1.IN:=FALSE;
			setpositionAxis1_State:=0;
			btn_SetPosition_Axis1:=FALSE;
		-100:
			PositionSetDone_Axis1:=FALSE;
			Axis1_MC_SetPosition.Execute:=FALSE;
			SetPosition_delay_Axis1.IN:=FALSE;
			btn_SetPosition_Axis1:=FALSE;
	END_CASE
END_IF
//Axis2
SetPosition_delay_Axis2.PT:=T#0.1S;
SetPosition_delay_Axis2();
IF btn_SetPosition_Axis2 THEN
	CASE setpositionAxis2_State OF 
		0:
			IF NOT  Axis2_running THEN
				setpositionAxis2_State:=1;
			END_IF
		1:
			Axis2_MC_SetPosition.Position:=PositionSetValue_Axis2;
			Axis2_MC_SetPosition.Execute:=TRUE;
			SetPosition_delay_Axis2.IN:=TRUE;
			setpositionAxis2_State:=2;
		2:
			IF Axis2_MC_SetPosition.Done THEN
				setpositionAxis2_State:=88;
			END_IF
			IF SetPosition_delay_Axis2.Q THEN//延时结束时，还没有设置位置成功
				setpositionAxis2_State:=-100;
			END_IF
		88:
			PositionSetDone_Axis2:=TRUE;
			Axis2_MC_SetPosition.Execute:=FALSE;
			SetPosition_delay_Axis2.IN:=FALSE;
			setpositionAxis2_State:=0;
			btn_SetPosition_Axis2:=FALSE;
		-100:
			PositionSetDone_Axis2:=FALSE;
			Axis2_MC_SetPosition.Execute:=FALSE;
			SetPosition_delay_Axis2.IN:=FALSE;
			btn_SetPosition_Axis2:=FALSE;
	END_CASE
END_IF
(*

(* 初始化程序，电机模式设定    *)
IF NOT initt THEN
	MC_SetPosition_axis1   :=Axis1_CurrentPosition_retain;
	MC_SetPosition_axis2   :=Axis2_CurrentPosition_retain;	   
	setposition1              :=TRUE;
	setposition2              :=TRUE;		
	initt                                :=TRUE;
END_IF;

IF NOT   Axis1_running  AND    Clear_CurrentPosition_Axis1 AND initt   THEN
     //mc_Home_axis1_Position              :=3.0;
     Clear_CurrentPosition_Axis11       :=TRUE;
     Clear_CurrentPosition_Axis1         :=FALSE;
END_IF;

IF NOT   Axis2_running   AND    Clear_CurrentPosition_Axis2 AND initt   THEN
     //mc_Home_axis2_Position              :=2.0;
     Clear_CurrentPosition_Axis22       :=TRUE;
     Clear_CurrentPosition_Axis2         :=FALSE;
END_IF;



IF NOT Axis1_running  AND  setposition11 AND dd AND NOT Clear_CurrentPosition_Axis1 THEN
 mc_Home_axis1_Position              :=mc_Home_axis1_Position1;
 Clear_CurrentPosition_Axis11       :=TRUE;;
  setposition11                                      :=FALSE;
END_IF;

IF NOT Axis2_running  AND  setposition22 AND dd AND NOT Clear_CurrentPosition_Axis2 THEN
 mc_Home_axis2_Position              :=mc_Home_axis2_Position1;
 Clear_CurrentPosition_Axis22       :=TRUE;;
  setposition22                                      :=FALSE;
END_IF;

mc_Home_axis1(
	Execute:=Clear_CurrentPosition_Axis11 ,
	Position:=mc_Home_axis1_Position,
	HomingMode:=MC_Direct ,//Sets the axis position directly to Position without executing a movement.
	BufferMode:= ,
	Options:= ,
	bCalibrationCam:= ,
	Axis:= axis1,
	Done=> Clear_done_Axis1,
	Busy=> ,
	Active=> ,
	CommandAborted=> ,
	Error=> ,
	ErrorID=> );

IF  Clear_done_Axis1 AND  Clear_CurrentPosition_Axis11  THEN
Clear_CurrentPosition_Axis11  :=FALSE;
Clear_done_Axis1                        :=FALSE;
END_IF;


mc_Home_axis2(
	Execute:=Clear_CurrentPosition_Axis22 ,
	Position:=mc_Home_axis2_Position ,
	HomingMode:=MC_Direct ,//Sets the axis position directly to Position without executing a movement.
	BufferMode:= ,
	Options:= ,
	bCalibrationCam:= ,
	Axis:= axis2,
	Done=> Clear_done_Axis2,
	Busy=> ,
	Active=> ,
	CommandAborted=> ,
	Error=> ,
	ErrorID=> );

IF  Clear_done_Axis2 AND  Clear_CurrentPosition_Axis22  THEN
Clear_CurrentPosition_Axis22  :=FALSE;
Clear_done_Axis2                       :=FALSE;
END_IF;



IF dd THEN

MC_SetPosition1(
	Execute:=setposition1 ,
	Position:=MC_SetPosition_axis1 ,
	Mode:=FALSE ,
	Options:= ,
	Axis:=axis1 ,
	Done=>setposition1_done ,
	Busy=> ,
	Error=> ,
	ErrorID=> );

MC_SetPosition2(
	Execute:=setposition2 ,
	Position:=MC_SetPosition_axis2 ,
	Mode:=FALSE ,
	Options:= ,
	Axis:=axis2 ,
	Done=>setposition2_done ,
	Busy=> ,
	Error=> ,
	ErrorID=> );


IF  setposition1_done    THEN
     setposition1                  :=FALSE ;
     setposition1_done      :=FALSE ;
END_IF;

IF  setposition2_done  THEN
     setposition2                 :=FALSE ;
     setposition2_done     :=FALSE ;
END_IF;

END_IF;

 SetPosition_delay(in := initt, pt := T#2s);
IF  SetPosition_delay.Q THEN
     dd   :=TRUE;
END_IF;
*)]]></ST>
    </Implementation>
    <Action Name="A_SetPositionMC" Id="{9afeaa97-7af6-44a0-91c2-9bb3ac449bed}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_SetPosition"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"Axis1_MC_SetPosition"</v>
                          <v n="Type">"MC_SetPosition"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">2L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">4L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">6L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">8L</v>
                            </o>
                            <v n="Id">7L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">10L</v>
                            </o>
                            <v n="Id">9L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">12L</v>
                            </o>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">14L</v>
                            </o>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"axis1"</v>
                              <v n="Type">"AXIS_REF"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">16L</v>
                            </o>
                            <v n="Id">15L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Position</v>
                            <v>Mode</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>BOOL</v>
                            <v>ST_SetPositionOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">3L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"MC_SetPosition"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"Axis2_MC_SetPosition"</v>
                          <v n="Type">"MC_SetPosition"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">18L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">20L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">21L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">22L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">24L</v>
                            </o>
                            <v n="Id">23L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">26L</v>
                            </o>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">28L</v>
                            </o>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <n n="Type" />
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">30L</v>
                            </o>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"axis2"</v>
                              <v n="Type">"AXIS_REF"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">32L</v>
                            </o>
                            <v n="Id">31L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Execute</v>
                            <v>Position</v>
                            <v>Mode</v>
                            <v>Options</v>
                            <v>Axis</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>LREAL</v>
                            <v>BOOL</v>
                            <v>ST_SetPositionOptions</v>
                            <v>AXIS_REF (VAR_IN_OUT)</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Done</v>
                            <v>Busy</v>
                            <v>Error</v>
                            <v>ErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">19L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">17L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="INIT">
      <LineId Id="368" Count="0" />
      <LineId Id="375" Count="1" />
      <LineId Id="439" Count="1" />
      <LineId Id="492" Count="0" />
      <LineId Id="369" Count="0" />
      <LineId Id="377" Count="0" />
      <LineId Id="467" Count="2" />
      <LineId Id="414" Count="0" />
      <LineId Id="476" Count="1" />
      <LineId Id="481" Count="0" />
      <LineId Id="478" Count="0" />
      <LineId Id="482" Count="0" />
      <LineId Id="480" Count="0" />
      <LineId Id="487" Count="0" />
      <LineId Id="475" Count="0" />
      <LineId Id="417" Count="1" />
      <LineId Id="420" Count="1" />
      <LineId Id="425" Count="2" />
      <LineId Id="422" Count="0" />
      <LineId Id="428" Count="2" />
      <LineId Id="505" Count="0" />
      <LineId Id="431" Count="1" />
      <LineId Id="434" Count="0" />
      <LineId Id="506" Count="0" />
      <LineId Id="485" Count="0" />
      <LineId Id="436" Count="0" />
      <LineId Id="378" Count="0" />
      <LineId Id="497" Count="0" />
      <LineId Id="493" Count="0" />
      <LineId Id="498" Count="3" />
      <LineId Id="503" Count="0" />
      <LineId Id="507" Count="1" />
      <LineId Id="502" Count="0" />
      <LineId Id="509" Count="0" />
      <LineId Id="495" Count="0" />
      <LineId Id="510" Count="1" />
      <LineId Id="623" Count="0" />
      <LineId Id="619" Count="0" />
      <LineId Id="618" Count="0" />
      <LineId Id="550" Count="0" />
      <LineId Id="512" Count="5" />
      <LineId Id="519" Count="0" />
      <LineId Id="521" Count="0" />
      <LineId Id="523" Count="1" />
      <LineId Id="526" Count="7" />
      <LineId Id="555" Count="0" />
      <LineId Id="535" Count="0" />
      <LineId Id="537" Count="1" />
      <LineId Id="560" Count="0" />
      <LineId Id="539" Count="0" />
      <LineId Id="557" Count="2" />
      <LineId Id="561" Count="0" />
      <LineId Id="494" Count="0" />
      <LineId Id="551" Count="0" />
      <LineId Id="622" Count="0" />
      <LineId Id="621" Count="0" />
      <LineId Id="620" Count="0" />
      <LineId Id="580" Count="29" />
      <LineId Id="579" Count="0" />
      <LineId Id="374" Count="0" />
      <LineId Id="367" Count="0" />
      <LineId Id="192" Count="3" />
      <LineId Id="197" Count="1" />
      <LineId Id="200" Count="14" />
      <LineId Id="219" Count="12" />
      <LineId Id="241" Count="41" />
      <LineId Id="301" Count="25" />
      <LineId Id="337" Count="9" />
      <LineId Id="357" Count="0" />
      <LineId Id="352" Count="4" />
      <LineId Id="5" Count="0" />
      <LineId Id="405" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>