<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="NOVRAM" Id="{5d91f566-ba50-433e-8d55-1c9ba1ba3ec9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM NOVRAM
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="NOVRAM">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>